package model;
// Generated 11/12/2016 20:59:30 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Nf generated by hbm2java
 */
@Entity
@Table(name="nf"
    ,schema="public"
)
public class Nf  implements java.io.Serializable {


     private int idNf;
     private int parcelamento;
     private float valorNf;
     private Integer numNf;
     private Set<Venda> vendas = new HashSet<Venda>(0);
     private Set<Parcelamento> parcelamentos = new HashSet<Parcelamento>(0);

    public Nf() {
    }

	
    public Nf(int idNf, int parcelamento, float valorNf) {
        this.idNf = idNf;
        this.parcelamento = parcelamento;
        this.valorNf = valorNf;
    }
    public Nf(int idNf, int parcelamento, float valorNf, Integer numNf, Set<Venda> vendas, Set<Parcelamento> parcelamentos) {
       this.idNf = idNf;
       this.parcelamento = parcelamento;
       this.valorNf = valorNf;
       this.numNf = numNf;
       this.vendas = vendas;
       this.parcelamentos = parcelamentos;
    }
   
     @Id 

    
    @Column(name="id_nf", unique=true, nullable=false)
    public int getIdNf() {
        return this.idNf;
    }
    
    public void setIdNf(int idNf) {
        this.idNf = idNf;
    }

    
    @Column(name="parcelamento", nullable=false)
    public int getParcelamento() {
        return this.parcelamento;
    }
    
    public void setParcelamento(int parcelamento) {
        this.parcelamento = parcelamento;
    }

    
    @Column(name="valor_nf", nullable=false, precision=8, scale=8)
    public float getValorNf() {
        return this.valorNf;
    }
    
    public void setValorNf(float valorNf) {
        this.valorNf = valorNf;
    }

    
    @Column(name="num_nf")
    public Integer getNumNf() {
        return this.numNf;
    }
    
    public void setNumNf(Integer numNf) {
        this.numNf = numNf;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="nf")
    public Set<Venda> getVendas() {
        return this.vendas;
    }
    
    public void setVendas(Set<Venda> vendas) {
        this.vendas = vendas;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="nf")
    public Set<Parcelamento> getParcelamentos() {
        return this.parcelamentos;
    }
    
    public void setParcelamentos(Set<Parcelamento> parcelamentos) {
        this.parcelamentos = parcelamentos;
    }




}


