package model;
// Generated 11/12/2016 20:59:30 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Parcelamento generated by hbm2java
 */
@Entity
@Table(name="parcelamento"
    ,schema="public"
)
public class Parcelamento  implements java.io.Serializable {


     private int idParcelamento;
     private Nf nf;
     private Parcela parcela;

    public Parcelamento() {
    }

    public Parcelamento(int idParcelamento, Nf nf, Parcela parcela) {
       this.idParcelamento = idParcelamento;
       this.nf = nf;
       this.parcela = parcela;
    }
   
     @Id 

    
    @Column(name="id_parcelamento", unique=true, nullable=false)
    public int getIdParcelamento() {
        return this.idParcelamento;
    }
    
    public void setIdParcelamento(int idParcelamento) {
        this.idParcelamento = idParcelamento;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_nf", nullable=false)
    public Nf getNf() {
        return this.nf;
    }
    
    public void setNf(Nf nf) {
        this.nf = nf;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_parcela", nullable=false)
    public Parcela getParcela() {
        return this.parcela;
    }
    
    public void setParcela(Parcela parcela) {
        this.parcela = parcela;
    }




}


