package model;
// Generated 11/12/2016 20:59:30 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Venda generated by hbm2java
 */
@Entity
@Table(name="venda"
    ,schema="public"
)
public class Venda  implements java.io.Serializable {


     private int idVenda;
     private Cliente cliente;
     private Nf nf;
     private Date dataVenda;

    public Venda() {
    }

    public Venda(int idVenda, Cliente cliente, Nf nf, Date dataVenda) {
       this.idVenda = idVenda;
       this.cliente = cliente;
       this.nf = nf;
       this.dataVenda = dataVenda;
    }
   
     @Id 

    
    @Column(name="id_venda", unique=true, nullable=false)
    public int getIdVenda() {
        return this.idVenda;
    }
    
    public void setIdVenda(int idVenda) {
        this.idVenda = idVenda;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="cliente", nullable=false)
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="nf", nullable=false)
    public Nf getNf() {
        return this.nf;
    }
    
    public void setNf(Nf nf) {
        this.nf = nf;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="data_venda", nullable=false, length=13)
    public Date getDataVenda() {
        return this.dataVenda;
    }
    
    public void setDataVenda(Date dataVenda) {
        this.dataVenda = dataVenda;
    }




}


